language: python
python:
- '3.6'
install:
- pip install numpy matplotlib
script:
- python performance.py
- ls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
